import type { Report, ReportListItem } from '@/types/api';
import { getReportTypeDisplayName } from './reports';
import { jsPDF } from 'jspdf';

/**
 * Generate a downloadable report summary as JSON
 */
export function downloadReportAsJson(report: Report | ReportListItem): void {
  const data = JSON.stringify(report, null, 2);
  const blob = new Blob([data], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = `report_${report.id}_${new Date().toISOString().split('T')[0]}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Generate and download a formatted text summary of the report
 */
export function downloadReportSummary(report: Report): void {
  const lines: string[] = [];
  
  // Header
  lines.push('═'.repeat(60));
  lines.push('MEDICAL REPORT SUMMARY');
  lines.push('═'.repeat(60));
  lines.push('');
  
  // Report Info
  lines.push('REPORT INFORMATION');
  lines.push('─'.repeat(40));
  lines.push(`Hospital: ${report.hospital_name || 'Not specified'}`);
  lines.push(`Doctor: ${report.doctor_name || report.metadata_extracted?.doctor_name || 'Not specified'}`);
  lines.push(`Report Date: ${report.report_date}`);
  lines.push(`Report Type: ${getReportTypeDisplayName(report.report_type)}`);
  if (report.document_type) {
    lines.push(`Document Type: ${report.document_type}`);
  }
  lines.push('');
  
  // Patient Info
  if (report.metadata_extracted?.patient_name) {
    lines.push('PATIENT INFORMATION');
    lines.push('─'.repeat(40));
    lines.push(`Name: ${report.metadata_extracted.patient_name}`);
    if (report.metadata_extracted.patient_age) {
      lines.push(`Age: ${report.metadata_extracted.patient_age} years`);
    }
    if (report.metadata_extracted.patient_gender) {
      lines.push(`Gender: ${report.metadata_extracted.patient_gender}`);
    }
    lines.push('');
  }
  
  // Patient-Friendly Summary
  if (report.patient_friendly_summary) {
    lines.push('PATIENT SUMMARY');
    lines.push('─'.repeat(40));
    lines.push(report.patient_friendly_summary);
    lines.push('');
  }
  
  // Clinical Summary
  if (report.clinical_summary) {
    lines.push('CLINICAL SUMMARY');
    lines.push('─'.repeat(40));
    lines.push(report.clinical_summary);
    lines.push('');
  }
  
  // Key Findings
  if (report.key_findings && report.key_findings.length > 0) {
    lines.push('KEY FINDINGS');
    lines.push('─'.repeat(40));
    report.key_findings.forEach((finding, i) => {
      lines.push(`${i + 1}. [${finding.severity.toUpperCase()}] ${finding.finding}`);
      if (finding.action_needed) {
        lines.push(`   Action: ${finding.action_needed}`);
      }
    });
    lines.push('');
  }
  
  // Test Results
  if (report.extracted_values && report.extracted_values.length > 0) {
    lines.push('TEST RESULTS');
    lines.push('─'.repeat(40));
    lines.push('');
    
    // Table header
    const headers = ['Test Name', 'Value', 'Unit', 'Reference', 'Status'];
    lines.push(headers.join(' | '));
    lines.push('─'.repeat(80));
    
    report.extracted_values.forEach((test) => {
      const value = test.value_numeric !== null ? String(test.value_numeric) : test.value_text;
      const reference = test.reference_text || 
        (test.reference_min !== null && test.reference_max !== null 
          ? `${test.reference_min} - ${test.reference_max}` 
          : '-');
      
      lines.push(`${test.test_name}`);
      lines.push(`  Value: ${value} ${test.unit || ''}`);
      lines.push(`  Reference: ${reference}`);
      lines.push(`  Status: ${test.status.toUpperCase()}`);
      lines.push(`  Confidence: ${test.confidence_score}%`);
      lines.push('');
    });
  }
  
  // Clinical Context
  if (report.extracted_data?.clinical_context) {
    const context = report.extracted_data.clinical_context;
    
    if (context.disease_information?.overview) {
      lines.push('CLINICAL CONTEXT');
      lines.push('─'.repeat(40));
      lines.push(context.disease_information.overview);
      lines.push('');
    }
    
    if (context.differential_diagnoses && context.differential_diagnoses.length > 0) {
      lines.push('DIFFERENTIAL DIAGNOSES');
      lines.push('─'.repeat(40));
      lines.push(context.differential_diagnoses.join(', '));
      lines.push('');
    }
    
    if (context.additional_notes) {
      lines.push('ADDITIONAL NOTES');
      lines.push('─'.repeat(40));
      lines.push(context.additional_notes);
      lines.push('');
    }
  }
  
  // Footer
  lines.push('═'.repeat(60));
  lines.push(`Generated by MedUnify on ${new Date().toLocaleString()}`);
  lines.push('═'.repeat(60));
  
  // Create and download file
  const content = lines.join('\n');
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  const hospitalName = (report.hospital_name || 'report').replace(/[^a-zA-Z0-9]/g, '_');
  link.download = `${hospitalName}_${report.report_date}_summary.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Download report as CSV (test results only)
 */
export function downloadReportAsCsv(report: Report): void {
  if (!report.extracted_values || report.extracted_values.length === 0) {
    alert('No test results available to download');
    return;
  }
  
  const headers = [
    'Test Name',
    'Standard Name',
    'Value',
    'Unit',
    'Reference Min',
    'Reference Max',
    'Reference Text',
    'Status',
    'Category',
    'Confidence Score',
    'Test Date'
  ];
  
  const rows = report.extracted_values.map((test) => [
    `"${test.test_name}"`,
    `"${test.standard_test_name || ''}"`,
    `"${test.value_numeric !== null ? test.value_numeric : test.value_text}"`,
    `"${test.unit || ''}"`,
    test.reference_min !== null ? test.reference_min : '',
    test.reference_max !== null ? test.reference_max : '',
    `"${test.reference_text || ''}"`,
    `"${test.status}"`,
    `"${test.category || ''}"`,
    test.confidence_score,
    `"${test.test_date || report.report_date}"`
  ]);
  
  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.join(','))
  ].join('\n');
  
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  const hospitalName = (report.hospital_name || 'report').replace(/[^a-zA-Z0-9]/g, '_');
  link.download = `${hospitalName}_${report.report_date}_results.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Download multiple reports as a combined JSON file
 */
export function downloadMultipleReports(reports: (Report | ReportListItem)[]): void {
  const data = JSON.stringify(reports, null, 2);
  const blob = new Blob([data], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = `medunify_reports_${new Date().toISOString().split('T')[0]}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Download report as PDF with formatted summary
 */
export function downloadReportAsPdf(report: Report): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let yPos = 20;
  
  // Helper to add text with word wrap
  const addText = (text: string, fontSize: number, isBold: boolean = false, color: [number, number, number] = [0, 0, 0]) => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    doc.setTextColor(color[0], color[1], color[2]);
    
    const lines = doc.splitTextToSize(text, contentWidth);
    
    // Check if we need a new page
    const lineHeight = fontSize * 0.5;
    if (yPos + lines.length * lineHeight > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.text(lines, margin, yPos);
    yPos += lines.length * lineHeight + 2;
  };
  
  // Helper to add a section header
  const addSectionHeader = (title: string) => {
    if (yPos > doc.internal.pageSize.getHeight() - 40) {
      doc.addPage();
      yPos = 20;
    }
    yPos += 5;
    doc.setDrawColor(34, 197, 94); // Green color
    doc.setLineWidth(0.5);
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 8;
    addText(title, 14, true, [34, 197, 94]);
    yPos += 2;
  };
  
  // Helper to add key-value pair
  const addKeyValue = (key: string, value: string) => {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(100, 100, 100);
    doc.text(key + ':', margin, yPos);
    
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    const keyWidth = doc.getTextWidth(key + ': ');
    const valueLines = doc.splitTextToSize(value, contentWidth - keyWidth);
    doc.text(valueLines, margin + keyWidth, yPos);
    yPos += valueLines.length * 5 + 3;
  };
  
  // Title
  doc.setFillColor(34, 197, 94);
  doc.rect(0, 0, pageWidth, 35, 'F');
  
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text('MedUnify', margin, 18);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Medical Report Summary', margin, 28);
  
  yPos = 50;
  
  // Report Information
  addSectionHeader('REPORT INFORMATION');
  addKeyValue('Hospital', report.hospital_name || 'Not specified');
  addKeyValue('Doctor', report.doctor_name || report.metadata_extracted?.doctor_name || 'Not specified');
  addKeyValue('Report Date', report.report_date);
  addKeyValue('Report Type', getReportTypeDisplayName(report.report_type));
  if (report.document_type) {
    addKeyValue('Document Type', report.document_type);
  }
  
  // Patient Information
  if (report.metadata_extracted?.patient_name) {
    addSectionHeader('PATIENT INFORMATION');
    addKeyValue('Name', report.metadata_extracted.patient_name);
    if (report.metadata_extracted.patient_age) {
      addKeyValue('Age', `${report.metadata_extracted.patient_age} years`);
    }
    if (report.metadata_extracted.patient_gender) {
      addKeyValue('Gender', report.metadata_extracted.patient_gender);
    }
  }
  
  // Patient-Friendly Summary
  if (report.patient_friendly_summary) {
    addSectionHeader('PATIENT SUMMARY');
    addText(report.patient_friendly_summary, 11);
  }
  
  // Clinical Summary
  if (report.clinical_summary) {
    addSectionHeader('CLINICAL SUMMARY');
    addText(report.clinical_summary, 11);
  }
  
  // Key Findings
  if (report.key_findings && report.key_findings.length > 0) {
    addSectionHeader('KEY FINDINGS');
    
    report.key_findings.forEach((finding, i) => {
      // Check for page break
      if (yPos > doc.internal.pageSize.getHeight() - 30) {
        doc.addPage();
        yPos = 20;
      }
      
      // Severity indicator
      let severityColor: [number, number, number];
      switch (finding.severity) {
        case 'low':
          severityColor = [34, 197, 94]; // Green
          break;
        case 'medium':
          severityColor = [234, 179, 8]; // Yellow
          break;
        case 'high':
        case 'critical':
          severityColor = [239, 68, 68]; // Red
          break;
        default:
          severityColor = [100, 100, 100];
      }
      
      doc.setFillColor(severityColor[0], severityColor[1], severityColor[2]);
      doc.circle(margin + 3, yPos - 2, 2, 'F');
      
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 0, 0);
      const findingLines = doc.splitTextToSize(`${i + 1}. ${finding.finding}`, contentWidth - 10);
      doc.text(findingLines, margin + 8, yPos);
      yPos += findingLines.length * 5 + 2;
      
      if (finding.action_needed) {
        doc.setFontSize(10);
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(100, 100, 100);
        const actionLines = doc.splitTextToSize(`Recommended: ${finding.action_needed}`, contentWidth - 15);
        doc.text(actionLines, margin + 12, yPos);
        yPos += actionLines.length * 4 + 4;
      }
    });
  }
  
  // Test Results
  if (report.extracted_values && report.extracted_values.length > 0) {
    addSectionHeader('TEST RESULTS');
    
    // Table header
    const colWidths = [55, 30, 20, 35, 25];
    const headers = ['Test Name', 'Value', 'Unit', 'Reference', 'Status'];
    
    doc.setFillColor(240, 240, 240);
    doc.rect(margin, yPos - 4, contentWidth, 8, 'F');
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(60, 60, 60);
    
    let xPos = margin;
    headers.forEach((header, i) => {
      doc.text(header, xPos + 2, yPos);
      xPos += colWidths[i];
    });
    yPos += 8;
    
    // Table rows
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    
    report.extracted_values.forEach((test) => {
      // Check for page break
      if (yPos > doc.internal.pageSize.getHeight() - 20) {
        doc.addPage();
        yPos = 20;
        
        // Repeat header on new page
        doc.setFillColor(240, 240, 240);
        doc.rect(margin, yPos - 4, contentWidth, 8, 'F');
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(60, 60, 60);
        xPos = margin;
        headers.forEach((header, i) => {
          doc.text(header, xPos + 2, yPos);
          xPos += colWidths[i];
        });
        yPos += 8;
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
      }
      
      xPos = margin;
      
      // Test name
      doc.setTextColor(0, 0, 0);
      const nameLines = doc.splitTextToSize(test.test_name, colWidths[0] - 4);
      doc.text(nameLines[0], xPos + 2, yPos);
      xPos += colWidths[0];
      
      // Value
      const value = test.value_numeric !== null ? String(test.value_numeric) : test.value_text;
      doc.text(value.substring(0, 12), xPos + 2, yPos);
      xPos += colWidths[1];
      
      // Unit
      doc.text(test.unit || '-', xPos + 2, yPos);
      xPos += colWidths[2];
      
      // Reference
      const reference = test.reference_text || 
        (test.reference_min !== null && test.reference_max !== null 
          ? `${test.reference_min}-${test.reference_max}` 
          : '-');
      doc.text(reference.substring(0, 15), xPos + 2, yPos);
      xPos += colWidths[3];
      
      // Status with color
      let statusColor: [number, number, number];
      switch (test.status) {
        case 'normal':
          statusColor = [34, 197, 94];
          break;
        case 'warning':
        case 'abnormal':
          statusColor = [234, 179, 8];
          break;
        case 'critical':
          statusColor = [239, 68, 68];
          break;
        default:
          statusColor = [100, 100, 100];
      }
      doc.setTextColor(statusColor[0], statusColor[1], statusColor[2]);
      doc.text(test.status.toUpperCase(), xPos + 2, yPos);
      
      yPos += 6;
      
      // Draw line
      doc.setDrawColor(230, 230, 230);
      doc.line(margin, yPos - 2, pageWidth - margin, yPos - 2);
    });
  }
  
  // Clinical Context
  if (report.extracted_data?.clinical_context) {
    const context = report.extracted_data.clinical_context;
    
    if (context.disease_information?.overview) {
      addSectionHeader('CLINICAL CONTEXT');
      addText(context.disease_information.overview, 10);
    }
    
    if (context.differential_diagnoses && context.differential_diagnoses.length > 0) {
      yPos += 3;
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(60, 60, 60);
      doc.text('Differential Diagnoses:', margin, yPos);
      yPos += 5;
      addText(context.differential_diagnoses.join(', '), 10);
    }
    
    if (context.additional_notes) {
      yPos += 3;
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(60, 60, 60);
      doc.text('Additional Notes:', margin, yPos);
      yPos += 5;
      doc.setFont('helvetica', 'italic');
      addText(context.additional_notes, 9, false, [80, 80, 80]);
    }
  }
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by MedUnify on ${new Date().toLocaleString()} | Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }
  
  // Save
  const hospitalName = (report.hospital_name || 'report').replace(/[^a-zA-Z0-9]/g, '_');
  doc.save(`${hospitalName}_${report.report_date}_summary.pdf`);
}
